### ISSUE TITLE
EPERM error on refresh

### ISSUE THREAD

**Issue by benjick** [meteor/windows-preview#106]
After modifying files this happens kinda often (maybe every other refresh)

```
=> Client modified -- refreshing
C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: EPERM, unlink 'C:\dev\school\.meteor\local\build\programs\web.browser\packages\jquery.js'
    at Object.Future.wait (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at Object.rm_recursive (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\files.js:268:9)
    at Object.files.rename (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\files.js:1384:13)
    at Object.files.renameDirAlmostAtomically (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\files.js:802:11)
    at [object Object]._.extend.complete (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\builder.js:482:11)
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\bundler.js:1819:11
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\bundler.js:2142:11
    at Function._.each._.forEach (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\bundler.js:2140:9
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.exports.bundle (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\bundler.js:2040:31)
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\run-app.js:554:24
    at time (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\profile.js:231:28)
    at Function.run (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\profile.js:377:12)
    at bundleApp (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\run-app.js:544:34)
    at [object Object]._.extend._runOnce (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\run-app.js:750:35)
    at [object Object]._.extend._fiber (C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\run-app.js:821:28)
    at C:\Users\mama\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\run-app.js:402:12
    - - - - -
C:\dev\school>meteor --version
WINDOWS-PREVIEW@0.3.0
C:\dev\school>meteor update
This project is already at WINDOWS-PREVIEW@0.3.0, the latest release.
Your packages are at their latest compatible versions.
```

**Comment by Slava** [comment]
Is it some particular application or any app? Do you know what is your file system type?

**Comment by benjick** [comment]
I can do some more testing tomorrow. I think it's when I delete files in the project but I'm not sure, I'll look into it some more. So far it's happened on both the projects I'm working on.

My file system is NTFS

**Comment by velum** [comment]
I got the same error on Windows 8 while simply following the tutorial. I had just finished adding the code on the first half of this page, and I was trying to add new tasks using the created app:

https://www.meteor.com/tutorials/blaze/forms-and-events

**Comment by velum** [comment]
OK, I found what it was. I had omitted the name="text" attribute in the text input. So my html template was looking as follows:

<head>
  <title>Todo List</title>
</head>

<body>
	<div class="container">
		<header>
			<h1>Todo List</h1>

			<form class="new-task">
				<input type="text" placeholder="Entrer une nouvelle tâche ici..." />
			</form>
		</header>

		<ul>
			{{#each tasks}}
				{{> task}}
			{{/each}}			
		</ul>
	</div>
</body>

<template name="task">
	<li>{{text}}</li>
</template>

But there was no error to give me a hint of what was happening. It was easy to pin-point my mistake is such a small example. However, I could imagine it becoming a nightmare in a very large project to have meteor crashing without any error message, or to have a form simply reloading the page without knowing why.

Here is the stack trace. The crash does not always happen, but if you omit the name attribute as I did and play with the app a bit, you should see meteor crashing at some point:

C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x8
6_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: EPERM, unlink 'C:\Users\JEAFB\Documents\Experiments\simple-todos\.meteor\
local\build\programs\.build888682.web.browser\packages\ddp.js'
    at Object.Future.wait (C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-
tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398
:15)
    at Object.rm_recursive (C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor
-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:268:9)
    at Object.files.rename (C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor
-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:1402:13)
    at Object.files.renameDirAlmostAtomically (C:\Users\JEAFB\AppData\Local\.met
eor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:818:9)
    at [object Object]._.extend.complete (C:\Users\JEAFB\AppData\Local\.meteor\p
ackages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\builder.js:482:11)
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\bundler.js:1819:11
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\bundler.js:2142:11
    at Function._.each._.forEach (C:\Users\JEAFB\AppData\Local\.meteor\packages\
meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\un
derscore.js:87:22)
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\bundler.js:2140:9
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\JEAFB\AppData\Local\.meteor\
packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\JEAFB\AppData\Local\.meteor\
packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\JEAFB\AppData\Local\.meteor\
packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\JEAFB\AppData\Local\.meteor\
packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool
\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.exports.bundle (C:\Users\JEAFB\AppData\Local\.meteor\packages\mete
or-tool\1.1.3\mt-os.windows.x86_32\tools\bundler.js:2040:31)
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\run-app.js:554:24
    at time (C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-
os.windows.x86_32\tools\profile.js:231:28)
    at Function.run (C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1
.1.3\mt-os.windows.x86_32\tools\profile.js:377:12)
    at bundleApp (C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.
3\mt-os.windows.x86_32\tools\run-app.js:544:34)
    at [object Object]._.extend._runOnce (C:\Users\JEAFB\AppData\Local\.meteor\p
ackages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:750:35)
    at [object Object]._.extend._fiber (C:\Users\JEAFB\AppData\Local\.meteor\pac
kages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:821:28)
    at C:\Users\JEAFB\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.win
dows.x86_32\tools\run-app.js:402:12
    - - - - -
