### ISSUE TITLE
Meteor worked, now it doesn't

### ISSUE THREAD

**Issue by BrooklynC** [meteor/windows-preview#117]
Closing this myself - should have read the message more closely after install and restarted my machine for Win 8.1

I was building an app using the previous Windows preview of Meteor and it was running great.  I just downloaded the version that came out on Friday.  I restarted WebStorm and ran meteor to start my app and received the errors below.  I am running Windows 8.1, not sure why these all refer to Windows 7.

If this is just a bug in the latest, I'd be fine going back a version, but could you let me know the best way to do that?  I'm just learning to write code, pretty narrow comfort zone.  Thanks.

C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: SQLITE_CORRUPT: database disk image is malformed
    at Object.Future.wait (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:395:16)
    at runOnce (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:237:21)
    at [object Object]._.extend._serialize (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:176:14)
    at [object Object]._.extend.runInTransaction (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:242:21)
    at [object Object]._.extend._columnsQuery (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:886:24)
    at [object Object]._.extend._contentQuery (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:876:21)
    at [object Object]._.extend.getReleaseVersion (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:663:23)
    at Object.release.load (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\release.js:233:41)
    at C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\main.js:891:23
    - - - - -
    at Object.Future.wait (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at [object Object]._.extend._query (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:312:22)
    at [object Object]._.extend.query (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:76:20)
    at C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:887:18
    at runOnce (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:211:18)
    at [object Object]._.extend._serialize (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:176:14)
    at [object Object]._.extend.runInTransaction (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:242:21)
    at [object Object]._.extend._columnsQuery (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:886:24)
    at [object Object]._.extend._contentQuery (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:876:21)
    at [object Object]._.extend.getReleaseVersion (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog-remote.js:663:23)
    at Object.release.load (C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\release.js:233:41)
    at C:\Users\Brendan F Cahill\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\main.js:891:23

**Comment by stubailo** [comment]
Hmm, interesting. I wonder what caused this problem! Since it's just a corrupt package database, reinstalling is a good thing to try when you run across things like this.
