### ISSUE TITLE
Exited with code: 8

### ISSUE THREAD

**Issue by gerardcarbo** [meteor/windows-preview#124]
After installing windows preview, I've tried it in a working project (on Linux) in Windows and I get:
```
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20150319-10:38:29.873(1)? (STDERR) C:\Users\gerard\AppData\Local\.meteor\packag
es\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modul
es\fibers\future.js:245
W20150319-10:38:29.873(1)? (STDERR)
throw(ex);
W20150319-10:38:29.873(1)? (STDERR)
      ^
W20150319-10:38:29.873(1)? (STDERR)     at [object Object].MongoInternals.Remote
CollectionDriver.open (packages/meteorhacks:collection-utils/index.js:5:1)
W20150319-10:38:29.873(1)? (STDERR) TypeError: Cannot call method 'bind' of unde
fined
W20150319-10:38:29.873(1)? (STDERR)     at new Mongo.Collection (packages/mongo/
collection.js:104:1)
W20150319-10:38:29.873(1)? (STDERR)     at app\lib\collections\config.js:4:10
W20150319-10:38:29.873(1)? (STDERR)     at E:\Art\code\Memslate\meteor\memslate\
.meteor\local\build\programs\server\boot.js:222:10
W20150319-10:38:29.873(1)? (STDERR)     at app\lib\collections\config.js:22:3
W20150319-10:38:29.873(1)? (STDERR)     at Array.forEach (native)
W20150319-10:38:29.873(1)? (STDERR)     at E:\Art\code\Memslate\meteor\memslate\
.meteor\local\build\programs\server\boot.js:117:5
W20150319-10:38:29.873(1)? (STDERR)     at Function._.each._.forEach (C:\Users\g
erard\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_3
2\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150319-10:38:29.873(1)? (STDERR)
```

**Comment by philcruz** [comment]
I'm getting the same error.

**Comment by stubailo** [comment]
I think looks like a bug in `meteorhacks:collection-utils` maybe?

**Comment by philcruz** [comment]
In my case differential:vulcanize was causing the problem. I removed it and the app started fine.

**Comment by philcruz** [comment]
Hmmm..after adding it back in I'm not getting the error anymore.

**Comment by gerardcarbo** [comment]
Yes, after updating all the packages, the problem was solved. Thanks
