### ISSUE TITLE
"meteor update" failing

### ISSUE THREAD

**Issue by ndarilek** [meteor/windows-preview#133]
Getting the following when attempting to update a 0.2.0 app to 0.3.0 with `meteor update`:

```
c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at Function._.has (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:1074:27)
    at [object Object]._.extend._loadUnibuildsFromPath (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\isopack.js:622:11)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\tropohouse.js:469:19
    at Array.forEach (native)
    at Function._.each._.forEach (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\tropohouse.js:468:11
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at Object.download (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\tropohouse.js:410:20)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\tropohouse.js:544:22
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\tropohouse.js:541:20)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\main.js:431:30
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog.js:96:5
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\catalog.js:95:31)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\main.js:430:17
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\main.js:428:33
    at [object Object]._.extend.withProgressDisplayVisible (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\console.js:612:14)
    at springboard (c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\main.js:427:11)
    at c:\Users\nolan\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\main.js:1005:5
```

**Comment by stubailo** [comment]
Yes, there were some issues in 0.2.0, so it is required to use the installer when updating to 0.3.0. That's why we are ironing out these issues now before the official release! Thanks for reporting.
