### ISSUE TITLE
Meteor crashes constantly.

### ISSUE THREAD

**Issue by fjafjan** [meteor/windows-preview#165]
I am building a fairly rather simple Meteor project on Windows 8, and despite both re-installing meteor, and manually re-setting the library, after the app has run for a short time meteor crashes and will not restart. Meteor is also unable to run reset, and I haven't been able to identify exactly what it is that causes this arise in the first place. There is a consistent error I get from the ccorcos:swipe, but runtime errors should not be crashing meteor right?

I have tried changing/removing the files in .meteor/client.

My question is both to identify what could be causing this particular error (what does "stat" mean in this context? other error messages I have found have while searching have been far more useful) as well as generally if there is a faster way of hard resetting a meteor project than running meteor create proj_name in a new folder and manually moving over the source files. 

The stacktrace is below.

The packages I use are 

 - meteor-platform 
 - insecure 
 - bevanhunt:leaflet 
 - mdg:geolocation
 - accounts-facebook
 - service-configuration 
 - less stevezhu:lodash
 - ccorcos:swipe
 - iron:router 
 - underscore 
 - coffeescript 
 - accounts-ui
 - accounts-password

    C:\Users\Fjafjan\Documents\GitHub\progress>meteor run
    [[[[[ C:\Users\Fjafjan\Documents\GitHub\progress ]]]]]

    => Started proxy.
    => Started MongoDB.

    C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                    throw(ex);
                                                          ^
    Error: EPERM, stat 'C:\Users\Fjafjan\Documents\GitHub\progress\.meteor\local\build\programs\web.browser\packages'
      at Object.Future.wait (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\
    fibers\future.js:398:15)
      at Object.wrapper [as stat] (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:1350:24
    )
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:454:43
      at Array.forEach (native)
      at Function._.each._.forEach (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_m
    odules\underscore\underscore.js:79:11)
      at Object.files.cp_r (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:444:5)
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:456:13
      at Array.forEach (native)
      at Function._.each._.forEach (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_m
    odules\underscore\underscore.js:79:11)
      at Object.files.cp_r (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:444:5)
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:456:13
      at Array.forEach (native)
      at Function._.each._.forEach (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_m
    odules\underscore\underscore.js:79:11)
      at Object.files.cp_r (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:444:5)
      at Object.files.rename (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:1401:13)
      at Object.files.renameDirAlmostAtomically (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fi
    les.js:810:11)
      at [object Object]._.extend.complete (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\builder
    .js:482:11)
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\bundler.js:1933:13
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\bundler.js:2147:20
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
      at [object Object]._.extend.withValue (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
    helpers.js:115:14)
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
      at [object Object]._.extend.withValue (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
    helpers.js:115:14)
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
      at [object Object]._.extend.withValue (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
    helpers.js:115:14)
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
      at [object Object]._.extend.withValue (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-
    helpers.js:115:14)
      at Object.capture (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
      at Object.exports.bundle (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\bundler.js:2040:31)

      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:554:24
      at time (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\profile.js:231:28)
      at Function.run (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\profile.js:377:12)
      at bundleApp (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:544:34)
      at [object Object]._.extend._runOnce (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app
    .js:591:35)
      at [object Object]._.extend._fiber (C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.j
    s:821:28)
      at C:\Users\Fjafjan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:402:12

**Comment by stumacd** [comment]
I am getting the same issue on Windows 7 - 64 bit machine.

**Comment by sdarnell** [comment]
In essence the code is trying to build a bundle ready for execution. During this process it is trying to be a good citizen by ensuring that you don't end up with a partial bundle in the case of an error.
It does this by building in a temporary folder, then 'atomically' renaming the folder to the final destination. (That's the renameDirAlmostAtomically in the stack trace)

This approach works well on unix like platforms, but doesn't always work well on Windows. The symptom is that when meteor tries to rename the folder, it is still in use, and you get an EPERM (permission denied error). So on Windows meteor has a fallback, and resorts to copying then deleting the original.
(That's the cp_r in the stack)

The copy should succeed, but for some reason it hasn't in this case - not sure why. Your line numbers don't quite line up with the current sources, so I'm not sure. But before it copies a file, it first check that it can 'stat' it. That is, read its file metadata.

Some scenarios can produce an EPERM if the file is 'scheduled for deletion', and this may be what is happening here - but it is difficult to tell.

As for resetting quicker, there is the `meteor reset` command, which should be really quick.

**Comment by stubailo** [comment]
I'm closing this repo. Moved here: https://github.com/meteor/meteor/issues/4933
