### ISSUE TITLE
velocity-examples doesn't work

### ISSUE THREAD

**Issue by hujhax** [meteor/windows-preview#21]
I tried downloading <a href="http://github.com/meteor-velocity/velocity-examples">the velocity example project</a>, as of fe90d0..., and running each of the velocity test programs using the Windows preview of meteor on a Windows 7 box.  Of the four (mocha, jasmine, cucumber, and nightwatch), only the nightwatch app ran.  (It listed nightwatch as having 0 tests, unfortunately.)  The other three wouldn't launch -- I've attached the results below.

====

### Mocha:

```
D:\Work\velocity-examples-master>cd leaderboard-mocha

D:\Work\velocity-examples-master\leaderboard-mocha>meteor
   removed practicalmeteor:chai from project
   removed practicalmeteor:loglevel from project
   removed velocity:node-soft-mirror from project
   removed velocity:shim from project
   removed velocity:test-proxy from project
   upgraded livedata from version 1.0.11 to version 1.0.12-win.0
   upgraded session from version 1.0.4 to version 1.0.5-win.0
   downgraded mike:mocha from version 0.5.0 to version 0.3.8
   upgraded spacebars-compiler from version 1.0.3 to version 1.0.4-win.0
   upgraded blaze from version 2.0.3 to version 2.0.4-win.0
   upgraded ordered-dict from version 1.0.1 to version 1.0.2-win.0
   upgraded spacebars from version 1.0.3 to version 1.0.4-win.0
   upgraded random from version 1.0.1 to version 1.0.2-win.0
   upgraded templating from version 1.0.9 to version 1.0.10-win.0
   upgraded coffeescript from version 1.0.4 to version 1.0.5-win.0
   upgraded mobile-status-bar from version 1.0.1 to version 1.0.2-win.0
   upgraded follower-livedata from version 1.0.2 to version 1.0.3-win.0
   upgraded deps from version 1.0.5 to version 1.0.6-win.0
   upgraded tracker from version 1.0.3 to version 1.0.4-win.0
   upgraded autoupdate from version 1.1.3 to version 1.1.4-win.0
   upgraded application-configuration from version 1.0.3 to version 1.0.4-win.0
   upgraded less from version 1.0.11 to version 1.0.12-win.0
   upgraded reload from version 1.1.1 to version 1.1.2-win.0
   upgraded launch-screen from version 1.0.0 to version 1.0.1-win.0
   upgraded underscore from version 1.0.1 to version 1.0.2-win.0
   upgraded ctl from version 1.0.2 to version 1.0.3-win.0
   upgraded retry from version 1.0.1 to version 1.0.2-win.0
   upgraded insecure from version 1.0.1 to version 1.0.2-win.0
   upgraded ctl-helper from version 1.0.4 to version 1.0.5-win.0
   upgraded http from version 1.0.8 to version 1.0.9-win.0
   upgraded json from version 1.0.1 to version 1.0.2-win.0
   upgraded check from version 1.0.2 to version 1.0.3-win.0
   upgraded boilerplate-generator from version 1.0.1 to version 1.0.2-win.0
   upgraded geojson-utils from version 1.0.1 to version 1.0.2-win.0
   upgraded standard-app-packages from version 1.0.3 to version 1.0.4-win.0
   upgraded logging from version 1.0.5 to version 1.0.6-win.0
   upgraded minimongo from version 1.0.5 to version 1.0.6-win.0
   upgraded jquery from version 1.0.1 to version 1.0.2-win.0
   upgraded id-map from version 1.0.1 to version 1.0.2-win.0
   upgraded reactive-dict from version 1.0.4 to version 1.0.5-win.0
   upgraded meteor from version 1.1.3 to version 1.1.4-win.0
   upgraded fastclick from version 1.0.1 to version 1.0.2-win.0
   upgraded webapp from version 1.1.4 to version 1.1.5-win.0
   upgraded ejson from version 1.0.4 to version 1.0.5-win.0
   upgraded routepolicy from version 1.0.2 to version 1.0.3-win.0
   upgraded base64 from version 1.0.1 to version 1.0.2-win.0
   upgraded url from version 1.0.2 to version 1.0.3-win.0
   upgraded html-tools from version 1.0.2 to version 1.0.3-win.0
   upgraded binary-heap from version 1.0.1 to version 1.0.2-win.0
   downgraded ddp from version 1.0.12 to version 1.0.12-win.0
   upgraded observe-sequence from version 1.0.3 to version 1.0.4-win.0
   upgraded reactive-var from version 1.0.3 to version 1.0.4-win.0
   upgraded webapp-hashing from version 1.0.1 to version 1.0.2-win.0
   upgraded meteor-platform from version 1.2.0 to version 1.2.1-win.0
   downgraded mongo from version 1.0.9 to version 1.0.9-win.0
   upgraded ui from version 1.0.4 to version 1.0.5-win.0
   upgraded htmljs from version 1.0.2 to version 1.0.3-win.0
   upgraded blaze-tools from version 1.0.1 to version 1.0.2-win.0
   upgraded minifiers from version 1.1.2 to version 1.1.3-win.0
   upgraded callback-hook from version 1.0.1 to version 1.0.2-win.0
=> Using WINDOWS-PREVIEW@0.0.10 as requested (overriding Meteor Meteor 1.0.1)

[[[[[ D:\Work\velocity-examples-master\leaderboard-mocha ]]]]]

=> Started proxy.
=> Started MongoDB.
W20150104-20:40:36.816(-6)? (STDERR)
W20150104-20:40:37.016(-6)? (STDERR) D:\Work\velocity-examples-master\leaderboar
d-mocha\.meteor\local\build\programs\server\node_modules\fibers\future.js:173
W20150104-20:40:37.023(-6)? (STDERR)
throw(ex);
W20150104-20:40:37.029(-6)? (STDERR)
      ^
W20150104-20:40:37.035(-6)? (STDERR) ReferenceError: Velocity is not defined
W20150104-20:40:37.038(-6)? (STDERR)     at Package (packages/mike:mocha/server.
js:7)
W20150104-20:40:37.044(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\packagesmike_mocha.js:342:4
W20150104-20:40:37.051(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\packagesmike_mocha.js:352:3
W20150104-20:40:37.057(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\boot.js:172:10
W20150104-20:40:37.063(-6)? (STDERR)     at Array.forEach (native)
W20150104-20:40:37.067(-6)? (STDERR)     at Function._.each._.forEach (D:\Work\v
elocity-examples-master\leaderboard-mocha\.meteor\local\build\programs\server\no
de_modules\underscore\underscore.js:79:11)
W20150104-20:40:37.076(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\boot.js:86:5
=> Exited with code: 8
W20150104-20:41:00.213(-6)? (STDERR)
W20150104-20:41:00.259(-6)? (STDERR) D:\Work\velocity-examples-master\leaderboar
d-mocha\.meteor\local\build\programs\server\node_modules\fibers\future.js:173
W20150104-20:41:00.266(-6)? (STDERR)
throw(ex);
W20150104-20:41:00.272(-6)? (STDERR)
      ^
W20150104-20:41:00.278(-6)? (STDERR) ReferenceError: Velocity is not defined
W20150104-20:41:00.281(-6)? (STDERR)     at Package (packages/mike:mocha/server.
js:7)
W20150104-20:41:00.287(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\packagesmike_mocha.js:342:4
W20150104-20:41:00.293(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\packagesmike_mocha.js:352:3
W20150104-20:41:00.300(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\boot.js:172:10
W20150104-20:41:00.307(-6)? (STDERR)     at Array.forEach (native)
W20150104-20:41:00.310(-6)? (STDERR)     at Function._.each._.forEach (D:\Work\v
elocity-examples-master\leaderboard-mocha\.meteor\local\build\programs\server\no
de_modules\underscore\underscore.js:79:11)
W20150104-20:41:00.319(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\boot.js:86:5
=> Exited with code: 8
W20150104-20:41:24.085(-6)? (STDERR)
W20150104-20:41:24.963(-6)? (STDERR) D:\Work\velocity-examples-master\leaderboar
d-mocha\.meteor\local\build\programs\server\node_modules\fibers\future.js:173
W20150104-20:41:24.969(-6)? (STDERR)
throw(ex);
W20150104-20:41:24.976(-6)? (STDERR)
      ^
W20150104-20:41:24.982(-6)? (STDERR) ReferenceError: Velocity is not defined
W20150104-20:41:24.986(-6)? (STDERR)     at Package (packages/mike:mocha/server.
js:7)
W20150104-20:41:24.992(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\packagesmike_mocha.js:342:4
W20150104-20:41:24.998(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\packagesmike_mocha.js:352:3
W20150104-20:41:25.005(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\boot.js:172:10
W20150104-20:41:25.011(-6)? (STDERR)     at Array.forEach (native)
W20150104-20:41:25.015(-6)? (STDERR)     at Function._.each._.forEach (D:\Work\v
elocity-examples-master\leaderboard-mocha\.meteor\local\build\programs\server\no
de_modules\underscore\underscore.js:79:11)
W20150104-20:41:25.023(-6)? (STDERR)     at D:\Work\velocity-examples-master\lea
derboard-mocha\.meteor\local\build\programs\server\boot.js:86:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
Terminate batch job (Y/N)? y
```

====

### Jasmine:

```
D:\Work\velocity-examples-master>cd leaderboard-jasmine

D:\Work\velocity-examples-master\leaderboard-jasmine>meteor
No compatible build found for sanjo:karma-chrome-launcher@0.1.5_1
No compatible build found for sanjo:karma-coffee-preprocessor@0.2.1
No compatible build found for sanjo:karma-jasmine@0.2.3
No compatible build found for sanjo:karma@0.12.24_2
No compatible build found for sanjo:karma-phantomjs-launcher-nonet@0.1.3
   upgraded livedata from version 1.0.11 to version 1.0.12-win.0
   upgraded session from version 1.0.4 to version 1.0.5-win.0
   upgraded spacebars-compiler from version 1.0.3 to version 1.0.4-win.0
   upgraded blaze from version 2.0.3 to version 2.0.4-win.0
   upgraded ordered-dict from version 1.0.1 to version 1.0.2-win.0
   upgraded spacebars from version 1.0.3 to version 1.0.4-win.0
   upgraded random from version 1.0.1 to version 1.0.2-win.0
   upgraded templating from version 1.0.9 to version 1.0.10-win.0
   upgraded mobile-status-bar from version 1.0.1 to version 1.0.2-win.0
   upgraded follower-livedata from version 1.0.2 to version 1.0.3-win.0
   upgraded deps from version 1.0.5 to version 1.0.6-win.0
   upgraded tracker from version 1.0.3 to version 1.0.4-win.0
   upgraded autoupdate from version 1.1.3 to version 1.1.4-win.0
   upgraded application-configuration from version 1.0.3 to version 1.0.4-win.0
   upgraded less from version 1.0.11 to version 1.0.12-win.0
   upgraded reload from version 1.1.1 to version 1.1.2-win.0
   upgraded launch-screen from version 1.0.0 to version 1.0.1-win.0
   upgraded underscore from version 1.0.1 to version 1.0.2-win.0
   upgraded ctl from version 1.0.2 to version 1.0.3-win.0
   upgraded velocity:core from version 0.3.0 to version 0.4.1
   upgraded autopublish from version 1.0.1 to version 1.0.2-win.0
   upgraded retry from version 1.0.1 to version 1.0.2-win.0
   upgraded insecure from version 1.0.1 to version 1.0.2-win.0
   upgraded ctl-helper from version 1.0.4 to version 1.0.5-win.0
   upgraded http from version 1.0.8 to version 1.0.9-win.0
   upgraded json from version 1.0.1 to version 1.0.2-win.0
   upgraded check from version 1.0.2 to version 1.0.3-win.0
   upgraded boilerplate-generator from version 1.0.1 to version 1.0.2-win.0
   upgraded geojson-utils from version 1.0.1 to version 1.0.2-win.0
   upgraded standard-app-packages from version 1.0.3 to version 1.0.4-win.0
   upgraded logging from version 1.0.5 to version 1.0.6-win.0
   upgraded minimongo from version 1.0.5 to version 1.0.6-win.0
   upgraded jquery from version 1.0.1 to version 1.0.2-win.0
   upgraded id-map from version 1.0.1 to version 1.0.2-win.0
   upgraded reactive-dict from version 1.0.4 to version 1.0.5-win.0
   upgraded meteor from version 1.1.3 to version 1.1.4-win.0
   upgraded fastclick from version 1.0.1 to version 1.0.2-win.0
   upgraded webapp from version 1.1.4 to version 1.1.5-win.0
   upgraded ejson from version 1.0.4 to version 1.0.5-win.0
   upgraded routepolicy from version 1.0.2 to version 1.0.3-win.0
   upgraded base64 from version 1.0.1 to version 1.0.2-win.0
   upgraded url from version 1.0.2 to version 1.0.3-win.0
   upgraded html-tools from version 1.0.2 to version 1.0.3-win.0
   upgraded binary-heap from version 1.0.1 to version 1.0.2-win.0
   upgraded ddp from version 1.0.11 to version 1.0.12-win.0
   upgraded observe-sequence from version 1.0.3 to version 1.0.4-win.0
   upgraded reactive-var from version 1.0.3 to version 1.0.4-win.0
   upgraded webapp-hashing from version 1.0.1 to version 1.0.2-win.0
   upgraded meteor-platform from version 1.2.0 to version 1.2.1-win.0
   upgraded mongo from version 1.0.8 to version 1.0.9-win.0
   upgraded ui from version 1.0.4 to version 1.0.5-win.0
   upgraded htmljs from version 1.0.2 to version 1.0.3-win.0
   upgraded blaze-tools from version 1.0.1 to version 1.0.2-win.0
   upgraded minifiers from version 1.1.2 to version 1.1.3-win.0
   upgraded callback-hook from version 1.0.1 to version 1.0.2-win.0
Could not install all the requested packages.

D:\Work\velocity-examples-master\leaderboard-jasmine>
```

====

### Cucumber:

```
D:\Work\velocity-examples-master>cd leaderboard-cucumber

D:\Work\velocity-examples-master\leaderboard-cucumber>meteor
   removed spacejamio:chai from project
   upgraded livedata from version 1.0.11 to version 1.0.12-win.0
   upgraded session from version 1.0.4 to version 1.0.5-win.0
   added practicalmeteor:chai at version 1.9.2_3
   upgraded spacebars-compiler from version 1.0.3 to version 1.0.4-win.0
   upgraded blaze from version 2.0.3 to version 2.0.4-win.0
   upgraded ordered-dict from version 1.0.1 to version 1.0.2-win.0
   upgraded spacebars from version 1.0.3 to version 1.0.4-win.0
   upgraded random from version 1.0.1 to version 1.0.2-win.0
   upgraded templating from version 1.0.9 to version 1.0.10-win.0
   upgraded mobile-status-bar from version 1.0.1 to version 1.0.2-win.0
   upgraded follower-livedata from version 1.0.2 to version 1.0.3-win.0
   upgraded deps from version 1.0.5 to version 1.0.6-win.0
   upgraded tracker from version 1.0.3 to version 1.0.4-win.0
   upgraded autoupdate from version 1.1.3 to version 1.1.4-win.0
   upgraded application-configuration from version 1.0.3 to version 1.0.4-win.0
   upgraded less from version 1.0.11 to version 1.0.12-win.0
   upgraded reload from version 1.1.1 to version 1.1.2-win.0
   upgraded launch-screen from version 1.0.0 to version 1.0.1-win.0
   upgraded underscore from version 1.0.1 to version 1.0.2-win.0
   upgraded ctl from version 1.0.2 to version 1.0.3-win.0
   upgraded retry from version 1.0.1 to version 1.0.2-win.0
   upgraded insecure from version 1.0.1 to version 1.0.2-win.0
   upgraded ctl-helper from version 1.0.4 to version 1.0.5-win.0
   upgraded http from version 1.0.8 to version 1.0.9-win.0
   upgraded json from version 1.0.1 to version 1.0.2-win.0
   upgraded check from version 1.0.2 to version 1.0.3-win.0
   upgraded boilerplate-generator from version 1.0.1 to version 1.0.2-win.0
   upgraded geojson-utils from version 1.0.1 to version 1.0.2-win.0
   upgraded standard-app-packages from version 1.0.3 to version 1.0.4-win.0
   upgraded logging from version 1.0.5 to version 1.0.6-win.0
   upgraded minimongo from version 1.0.5 to version 1.0.6-win.0
   upgraded jquery from version 1.0.1 to version 1.0.2-win.0
   upgraded id-map from version 1.0.1 to version 1.0.2-win.0
   upgraded reactive-dict from version 1.0.4 to version 1.0.5-win.0
   upgraded meteor from version 1.1.3 to version 1.1.4-win.0
   upgraded fastclick from version 1.0.1 to version 1.0.2-win.0
   upgraded webapp from version 1.1.4 to version 1.1.5-win.0
   upgraded ejson from version 1.0.4 to version 1.0.5-win.0
   upgraded routepolicy from version 1.0.2 to version 1.0.3-win.0
   upgraded practicalmeteor:loglevel from version 1.1.0_2 to version 1.1.0_3
   upgraded base64 from version 1.0.1 to version 1.0.2-win.0
   upgraded url from version 1.0.2 to version 1.0.3-win.0
   upgraded html-tools from version 1.0.2 to version 1.0.3-win.0
   upgraded binary-heap from version 1.0.1 to version 1.0.2-win.0
   upgraded ddp from version 1.0.11 to version 1.0.12-win.0
   upgraded coffeescript from version 1.0.4 to version 1.0.5-win.0
   upgraded observe-sequence from version 1.0.3 to version 1.0.4-win.0
   upgraded reactive-var from version 1.0.3 to version 1.0.4-win.0
   upgraded webapp-hashing from version 1.0.1 to version 1.0.2-win.0
   upgraded meteor-platform from version 1.2.0 to version 1.2.1-win.0
   upgraded mongo from version 1.0.8 to version 1.0.9-win.0
   upgraded ui from version 1.0.4 to version 1.0.5-win.0
   upgraded htmljs from version 1.0.2 to version 1.0.3-win.0
   upgraded blaze-tools from version 1.0.1 to version 1.0.2-win.0
   upgraded minifiers from version 1.1.2 to version 1.1.3-win.0
   upgraded callback-hook from version 1.0.1 to version 1.0.2-win.0
=> Using WINDOWS-PREVIEW@0.0.10 as requested (overriding Meteor Meteor 1.0)

[[[[[ D:\Work\velocity-examples-master\leaderboard-cucumber ]]]]]

=> Started proxy.
=> Started MongoDB.
W20150104-20:45:02.992(-6)? (STDERR)
W20150104-20:45:03.131(-6)? (STDERR) D:\Work\velocity-examples-master\leaderboar
d-cucumber\.meteor\local\build\programs\server\node_modules\fibers\future.js:173

W20150104-20:45:03.145(-6)? (STDERR)
throw(ex);
W20150104-20:45:03.155(-6)? (STDERR)
      ^
W20150104-20:45:03.164(-6)? (STDERR) TypeError: Arguments to path.join must be s
trings
W20150104-20:45:03.170(-6)? (STDERR)     at f (path.js:204:15)
W20150104-20:45:03.175(-6)? (STDERR)     at Object.filter (native)
W20150104-20:45:03.180(-6)? (STDERR)     at Object.exports.join (path.js:209:40)

W20150104-20:45:03.187(-6)? (STDERR)     at Object._.extend.start (packages/velo
city:node-soft-mirror/nodeMirrorServer.js:61)
W20150104-20:45:03.195(-6)? (STDERR)     at _startOrReuseMirror (packages/veloci
ty:core/mirrors/Mirror.js:222)
W20150104-20:45:03.202(-6)? (STDERR)     at Meteor.methods.velocity/mirrors/requ
est (packages/velocity:core/mirrors/Mirror.js:84)
W20150104-20:45:03.210(-6)? (STDERR)     at maybeAuditArgumentChecks (packages/d
dp/livedata_server.js:1599)
W20150104-20:45:03.218(-6)? (STDERR)     at packages/ddp/livedata_server.js:1513

W20150104-20:45:03.226(-6)? (STDERR)     at _.extend.withValue (packages/meteor/
dynamics_nodejs.js:56)
W20150104-20:45:03.233(-6)? (STDERR)     at _.extend.apply (packages/ddp/livedat
a_server.js:1512)
=> Exited with code: 8
W20150104-20:45:41.073(-6)? (STDERR)
W20150104-20:45:41.078(-6)? (STDERR) D:\Work\velocity-examples-master\leaderboar
d-cucumber\.meteor\local\build\programs\server\node_modules\fibers\future.js:173

W20150104-20:45:41.090(-6)? (STDERR)
throw(ex);
W20150104-20:45:41.097(-6)? (STDERR)
      ^
W20150104-20:45:41.108(-6)? (STDERR) TypeError: Arguments to path.join must be s
trings
W20150104-20:45:41.116(-6)? (STDERR)     at f (path.js:204:15)
W20150104-20:45:41.121(-6)? (STDERR)     at Object.filter (native)
W20150104-20:45:41.125(-6)? (STDERR)     at Object.exports.join (path.js:209:40)

W20150104-20:45:41.133(-6)? (STDERR)     at Object._.extend.start (packages/velo
city:node-soft-mirror/nodeMirrorServer.js:61)
W20150104-20:45:41.149(-6)? (STDERR)     at _startOrReuseMirror (packages/veloci
ty:core/mirrors/Mirror.js:222)
W20150104-20:45:41.158(-6)? (STDERR)     at Meteor.methods.velocity/mirrors/requ
est (packages/velocity:core/mirrors/Mirror.js:84)
W20150104-20:45:41.169(-6)? (STDERR)     at maybeAuditArgumentChecks (packages/d
dp/livedata_server.js:1599)
W20150104-20:45:41.178(-6)? (STDERR)     at packages/ddp/livedata_server.js:1513

W20150104-20:45:41.188(-6)? (STDERR)     at _.extend.withValue (packages/meteor/
dynamics_nodejs.js:56)
W20150104-20:45:41.196(-6)? (STDERR)     at _.extend.apply (packages/ddp/livedat
a_server.js:1512)
=> Exited with code: 8
W20150104-20:46:26.626(-6)? (STDERR)
W20150104-20:46:26.637(-6)? (STDERR) D:\Work\velocity-examples-master\leaderboar
d-cucumber\.meteor\local\build\programs\server\node_modules\fibers\future.js:173

W20150104-20:46:26.638(-6)? (STDERR)
throw(ex);
W20150104-20:46:26.639(-6)? (STDERR)
      ^
W20150104-20:46:26.640(-6)? (STDERR) TypeError: Arguments to path.join must be s
trings
W20150104-20:46:26.640(-6)? (STDERR)     at f (path.js:204:15)
W20150104-20:46:26.641(-6)? (STDERR)     at Object.filter (native)
W20150104-20:46:26.642(-6)? (STDERR)     at Object.exports.join (path.js:209:40)

W20150104-20:46:26.643(-6)? (STDERR)     at Object._.extend.start (packages/velo
city:node-soft-mirror/nodeMirrorServer.js:61)
W20150104-20:46:26.644(-6)? (STDERR)     at _startOrReuseMirror (packages/veloci
ty:core/mirrors/Mirror.js:222)
W20150104-20:46:26.645(-6)? (STDERR)     at Meteor.methods.velocity/mirrors/requ
est (packages/velocity:core/mirrors/Mirror.js:84)
W20150104-20:46:26.646(-6)? (STDERR)     at maybeAuditArgumentChecks (packages/d
dp/livedata_server.js:1599)
W20150104-20:46:26.647(-6)? (STDERR)     at packages/ddp/livedata_server.js:1513

W20150104-20:46:26.647(-6)? (STDERR)     at _.extend.withValue (packages/meteor/
dynamics_nodejs.js:56)
W20150104-20:46:26.648(-6)? (STDERR)     at _.extend.apply (packages/ddp/livedat
a_server.js:1512)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
Terminate batch job (Y/N)? y

D:\Work\velocity-examples-master\leaderboard-cucumber>
```

**Comment by Slava** [comment]
I think this is something you need to report to the Velocity people. The project is maintained outside of MDG.

**Comment by rdickert** [comment]
@hujhax I'm involved with the Velocity project and have posted about this issue [on the velocity-core list](https://groups.google.com/forum/#!topic/velocity-core/SdIn4C_I_WQ). Would love it if you'd drop a message there. Velocity is made up of several independently-maintained frameworks as well as the central test runner, so I think to begin with we should discuss with the whole group.

**Comment by hujhax** [comment]
(@rdickert: Okay, I added a note there -- thanks!)
