### ISSUE TITLE
Can't use local packages with npm dependencies

### ISSUE THREAD

**Issue by emgee3** [meteor/windows-preview#5]
Local packages with npm dependencies don't seem to work. I get the following error message:

    C:\meteor\test-app>meteor
       added mssql at version 1.0.0
    [[[[[ C:\meteor\test-app ]]]]]

    => Started proxy.
    => Started MongoDB.
    mssql: updating npm dependencies -- mssql...

    module.js:340
        throw err;
              ^
    Error: Cannot find module 'isarray'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.0.35-win.16\meteor-tool-os.windows.x86_32\dev_bundle\bin\node_modules\npm\node_modules\npm-registry-client\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_readable.js:25:15)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        
There are two separate local packages, `cheerio` and `mssql` both give the same error.

Running Windows Server 2008 R2 SP1 x64, up to date Windows Updates.

Reproduction: https://github.com/emgee3/windows-preview-issue-5-repro

This works on OS X after updating to `METEOR@1.0`.

**Comment by stubailo** [comment]
Try the new preview release 0.0.27: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

This issue might be fixed now.

**Comment by emgee3** [comment]
Thanks @stubailo, this now works.
