### ISSUE TITLE
TypeError after meteor-tool update

### ISSUE THREAD

**Issue by benjick** [meteor/windows-preview#90]
Hi guys.

When I created a new project today meteor-tool downloaded an update and I got this error, whichever command I'm running with meteor.

```
E:\dev>meteor help
 
C:\Users\max_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\server\mini-files.js:18
  if (p[0] === "\\" && (! partialPath)) {
      ^
TypeError: Cannot read property '0' of undefined
   at toPosixPath (C:\Users\max_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\server\mini-files.js:18:8)
   at Object.convertToStandardPath (C:\Users\max_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\server\mini-files.js:5
5:12)
   at Object.files.getHomeDir (C:\Users\max_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\files.js:1165:13)
   at defaultWarehouseDir (C:\Users\max_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\tropohouse.js:30:43)
   at Object.<anonymous> (C:\Users\max_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\tropohouse.js:39:42)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
```

**Comment by benjick** [comment]
Sorry. reinstalled it from https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows and it works now

**Comment by stubailo** [comment]
In the future, you shouldn't have to reinstall using the installer, but we broke something about updating in `WINDOWS-PREVIEW@0.1.7` which resulted in this bug.
